### ISSUE TITLE
Angular 14

### ISSUE THREAD

**Issue by jmbarbier** [lekhmanrus/ngx-pug-builders#4]
### Feature Description

Angular 14 seems to be well supported by ngx-pug-builders using --force

warning " > ngx-pug-builders@13.1.0" has incorrect peer dependency "@angular-devkit/build-angular@^13.1.4".
warning " > ngx-pug-builders@13.1.0" has incorrect peer dependency "@angular/compiler-cli@^13.1.3".

could you release a ngx-pug-builders with 14 as peer dep ?
thank you for this valuable piece of code

**Comment by lekhmanrus** [comment]
Hi @jmbarbier,
Thank you! Just released [v14.0.0](https://github.com/lekhmanrus/ngx-pug-builders/releases/tag/v14.0.0). 🙂
