### ISSUE TITLE
Angular 15 support / breaking changes

### ISSUE THREAD

**Issue by jmbarbier** [lekhmanrus/ngx-pug-builders#5]
### Feature Description

Some infos on ngx-pug-builders and ng15

Tested with new angular 15, build / serve are OK.

ng test have problems as ng test outputs "Error: Specified patterns: "" did not match any spec files."

this is because of https://github.com/angular/angular-cli/commit/dbcea96274122db128099967fec3d1ecceafe1ab

two steps needed :
- adding the missing line `"default": ["**/*.spec.ts"]` in ngx-pug-builders karma/schema.json as in https://github.com/angular/angular-cli/commit/dbcea96274122db128099967fec3d1ecceafe1ab#diff-e4ee8d37e407771a03c6d8120841d855c106bf48c969a5dc5ef8a0db41bbe79c
- removing the lines in tests.ts as in https://github.com/angular/angular-cli/commit/dbcea96274122db128099967fec3d1ecceafe1ab#diff-93fac08c03cc68a6a3217be53262dccc4ccc6bd6909c397fb1ca32f18fae5182

The first one is a one-liner into ngx-pug-builders code, the second one is changed by ng update, but not when using ngx-pug-builders, so it would eventually need a note in README ?

Until an ngx-pug-builders v15, changing tests.ts and calling `ng test --include '**/*.ts'` should be enough

### Use Case

Use ngx-pug-builders with ng 15

**Comment by lekhmanrus** [comment]
Hi @jmbarbier,
Thank you! Just released [v15.0.0](https://github.com/lekhmanrus/ngx-pug-builders/releases/tag/v15.0.0). 🙂
