### ISSUE TITLE
Angular 15+ Template Concatenation

### ISSUE THREAD

**Issue by lixaotec** [lekhmanrus/ngx-pug-builders#6]
### Documentation Feedback

Dear fellows, 

I start by apologize as I know this might not be the best place to seek help.

Just noticed that your lib accomplish something I was looking for.

I need to get angular to concatenate templates in a component, and I could do that until v9- by simply using import template from './temp.html' and then at @Component directive by template: template1 + template2 .. it used to work.

However I cant do that more in v13+ 

Could you provide me some help in order to achieve that?

Thank you so much

**Comment by lekhmanrus** [comment]
Hi @lixaotec,

You  can simply have
```ts
@Component({
  templateUrl: './test.pug',
  //  ...
})
```

and inside your `test.pug`
```pug
include ./a
include ./b
```
