### ISSUE TITLE
Support vscode + angular + pug

### ISSUE THREAD

**Issue by cooledcrrc13** [lekhmanrus/ngx-pug-builders#7]
### Feature Description

Hello,
Is a option to support pug template with angular on vs code ? Now is a problem with go to component by template reference (tag)

Is any option to resolve this problem in vs code ?

### Use Case

If we have small project with a few component is not a problem because can use a vs code command line, but when we change a project to large/new where we have a lot of components is problem to find component, yes we can use a command line but sometimes the file name is not the same as template selector or we have multiple selector with the same name but in other modules.

**Comment by lekhmanrus** [comment]
Hi @cooledcrrc13,
Thank you for your suggestion! At this moment I do not have any timeline on that. That is definitely good suggestion and I would like to work on that some time later, but just not on my radar currently.
