### ISSUE TITLE
Angular 16

### ISSUE THREAD

**Issue by jmbarbier** [lekhmanrus/ngx-pug-builders#8]
### Feature Description

ngx-pug-builders works perfectly with angular 16 (tested with all rc versions, and today with final 16.0.0), without any change. Could you bump the angular peer dep to allow smooth ng16 ng update without --force ? Thank you !

**Comment by lekhmanrus** [comment]
Hi @jmbarbier,
Thanks, I'll definitely do that today-tomorrow.
